### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by anewton1998** [gbxyz/rdapper#10]
What is the license for this software? There does not seem to be a LICENSE file or any header that states the license.

**Comment by gbxyz** [comment]
The copyright and license statement may be found in [README.md](https://github.com/gbxyz/rdapper/blob/master/README.md) and at the bottom of [rdapper.pm](https://github.com/gbxyz/rdapper/blob/master/lib/App/rdapper.pm).

rdapper is licensed under [the same terms as Perl](https://dev.perl.org/licenses/), that is, you can choose between [any version of the GPL](http://www.fsf.org/licenses/licenses.html#GNUGPL) or the [Artistic License](https://dev.perl.org/licenses/artistic.html).
