### ISSUE TITLE
Makefile.PL declares "freebsd" license

### ISSUE THREAD

**Issue by ppisar** [gbxyz/rdapper#8]
All files refer to the Perl license, but Makefile.PL has a different opinion:

~~~~
$ git grep -i freebsd
Makefile.PL:    'LICENSE'               => 'freebsd',
~~~~

It looks like a mistake (commit 764fbcabf6ac5bb8a26042772251ad8f9e9d7ea1).

**Comment by gbxyz** [comment]
Thanks, this is fixed.
